name: impc_abr
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pandas=2.2.2
  - matplotlib-inline=0.1.7
  - pip:
    - arviz==0.20.0
    - matplotlib==3.10.0
    - pymc==5.20.0
    - scikit-learn==1.6.1
    - scipy==1.15.1
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - tqdm==4.66.5
    - torch==2.7.1+cu128