"""
Assertion-level acoustic filtering.

Instead of classifying whole MP terms, this module filters individual
genotype-phenotype assertions that were generated by acoustic-dependent
procedures. Gene-to-MP mappings rebuilt from the filtered data naturally
exclude acoustic contributions without any arbitrary threshold.

For mixed procedures (CSD/SHIRPA), only assertions with acoustic-specific
MP terms (pinna reflex, startle) are removed; non-acoustic assertions
(gait, coat morphology) from the same procedure are retained.
"""

import logging
from collections import defaultdict

import pandas as pd

logger = logging.getLogger(__name__)

# Fully acoustic procedures — all assertions removed
ACOUSTIC_PROC_PATTERNS = ["ACS", "IMPC_ABR_", "ESLIM_011"]

# Mixed procedures (CSD/SHIRPA) — only acoustic-specific MP terms removed
MIXED_PROC_PATTERNS = ["CSD", "SHI", "ESLIM_008", "M-G-P_008"]

# MP term keywords that are acoustic-dependent when from mixed procedures
ACOUSTIC_MP_KEYWORDS = [
    "pinna reflex",
    "preyer",
    "startle reflex",
    "startle response",
    "acoustic startle",
]


def _is_fully_acoustic_proc(proc_id):
    """Check if a procedure is fully acoustic-dependent (all assertions removed)."""
    if not proc_id:
        return False
    return any(pattern in str(proc_id) for pattern in ACOUSTIC_PROC_PATTERNS)


def _is_mixed_proc(proc_id):
    """Check if a procedure is mixed (CSD/SHIRPA — partial removal)."""
    if not proc_id:
        return False
    return any(pattern in str(proc_id) for pattern in MIXED_PROC_PATTERNS)


def _is_acoustic_mp_term(mp_term_name, int_mp_names=None):
    """Check if a specific MP term is acoustic-dependent (for mixed procedures)."""
    name_lower = str(mp_term_name).lower()
    # Check leaf term name
    if any(kw in name_lower for kw in ACOUSTIC_MP_KEYWORDS):
        return True
    # Check intermediate term names
    if int_mp_names:
        if isinstance(int_mp_names, str):
            int_mp_names = [int_mp_names]
        if isinstance(int_mp_names, list):
            all_names = " ".join(str(n).lower() for n in int_mp_names)
            if any(kw in all_names for kw in ACOUSTIC_MP_KEYWORDS):
                return True
    return False


def filter_acoustic_assertions(gp_df):
    """Filter genotype-phenotype assertions to remove acoustic-dependent evidence.

    - Fully acoustic procedures (ACS, ABR, ESLIM_011): ALL assertions removed
    - Mixed procedures (CSD/SHIRPA): only assertions with acoustic MP terms removed
    - All other procedures: retained

    Args:
        gp_df: genotype-phenotype DataFrame from IMPC API

    Returns:
        filtered_df: DataFrame with acoustic assertions removed
        removal_log: DataFrame logging what was removed and why
    """
    keep_mask = []
    log_rows = []

    for idx, row in gp_df.iterrows():
        proc_id = row.get("procedure_stable_id", "")
        if isinstance(proc_id, list):
            proc_id = proc_id[0] if proc_id else ""

        proc_name = str(row.get("procedure_name", ""))
        gene = row.get("marker_symbol", "")
        mp_name = str(row.get("mp_term_name", ""))
        int_names = row.get("intermediate_mp_term_name", [])

        if _is_fully_acoustic_proc(proc_id):
            keep_mask.append(False)
            log_rows.append(
                {
                    "gene": gene,
                    "procedure": proc_id,
                    "procedure_name": proc_name,
                    "mp_term": mp_name,
                    "action": "removed",
                    "reason": "fully acoustic procedure",
                }
            )
        elif _is_mixed_proc(proc_id):
            if _is_acoustic_mp_term(mp_name, int_names):
                keep_mask.append(False)
                log_rows.append(
                    {
                        "gene": gene,
                        "procedure": proc_id,
                        "procedure_name": proc_name,
                        "mp_term": mp_name,
                        "action": "removed",
                        "reason": "acoustic MP term from mixed procedure",
                    }
                )
            else:
                keep_mask.append(True)
                log_rows.append(
                    {
                        "gene": gene,
                        "procedure": proc_id,
                        "procedure_name": proc_name,
                        "mp_term": mp_name,
                        "action": "kept",
                        "reason": "non-acoustic MP term from mixed procedure",
                    }
                )
        else:
            keep_mask.append(True)
            # Don't log every kept assertion — too many

    filtered_df = gp_df[keep_mask].copy()
    removal_log = pd.DataFrame(log_rows)

    n_removed = len(gp_df) - len(filtered_df)
    n_acoustic_proc = sum(
        1 for r in log_rows if r["reason"] == "fully acoustic procedure"
    )
    n_mixed_removed = sum(
        1 for r in log_rows if r["reason"] == "acoustic MP term from mixed procedure"
    )
    n_mixed_kept = sum(
        1
        for r in log_rows
        if r["reason"] == "non-acoustic MP term from mixed procedure"
    )

    logger.info(f"Acoustic assertion filtering:")
    logger.info(f"  Total assertions: {len(gp_df):,}")
    logger.info(f"  Removed (fully acoustic procs): {n_acoustic_proc:,}")
    logger.info(f"  Removed (acoustic terms from mixed procs): {n_mixed_removed:,}")
    logger.info(f"  Kept (non-acoustic terms from mixed procs): {n_mixed_kept:,}")
    logger.info(f"  Total removed: {n_removed:,}")
    logger.info(f"  Remaining: {len(filtered_df):,}")

    return filtered_df, removal_log
